Repository mainheartng/backend-api, pull requests merged in 2023-01, with the labels that each got.

#9 Updating staging branch with directories
  src/.gitkeep
  src/config/.gitkeep
  src/controllers/.gitkeep
  src/middlewares/.gitkeep
  src/models/.gitkeep
  src/routes/.gitkeep
  src/services/.gitkeep
  src/util/.gitkeep
Labels: in-progress, completed

#12 feat: added little description for the readme
  README.md
Labels: enhancement

#13 API dependencies
  package-lock.json
  package.json
Labels: in-progress, change-requested

#18 feat: add npm script
  index.js
  package.json
Labels: in-progress, feature

#17 feat: add and configure husky for git linting
  .husky/commit-msg
  commitlint.config.cjs
  package-lock.json
  package.json
Labels: enhancement, review-require, in-progress, feature, priority-high, feature-request

#19 Feat: create entry point
  index.js
  package-lock.json
  package.json
Labels: todo, feature, roadmap
