Repository mainheartng/backend-api, pull requests merged in 2023-02, with the labels that each got.

#25 Feat: 20 add a return object to index
  index.js
Labels: feature, fix

#29 feat: 16 add and configure eslint
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: enhancement, in-progress, feature, roadmap

#21 RoadMap: Moving code to test deployment env
  .eslintrc.cjs
  .husky/commit-msg
  README.md
  commitlint.config.cjs
  index.js
  package-lock.json
  package.json
Labels: review-require, attention-needed, feature, roadmap, priority-high

#38 feat: implement github actions
  .github/workflows/check-and.yml
Labels: feature, roadmap
